### ISSUE TITLE
Variable up the row padding and update related components

### ISSUE THREAD

**Issue by anthonydillon** [ubuntudesign/vanilla-framework#73] opened 2015-03-01 21:52 UTC
```.link-top``` a needs margin-top: -35px as the rows padding has changed. We should set the row padding with variables in the scss therefore auto updating all components that need it.

**Comment by yaili** [comment] 2016-05-09 14:15
@anthonydillon Has this been address yet?

**Comment by anthonydillon** [comment] 2016-05-09 14:43
No I dont think it has been yet.

**Comment by barrymcgee** [comment] 2016-08-16 11:39
This is a duplicate of #276

**Closed by barrymcgee** 2016-08-16 11:39 UTC
Labels: Status: Triaged, Type: Bug
