### ISSUE TITLE
[Proposal] Minor grid improvements

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/vanilla-framework#733] opened 2017-01-06 11:21 UTC
@anthonydillon please expand

**Comment by anthonydillon** [comment] 2017-01-06 11:55
Due to the following issues:
- Only the first column has no margin-left so we cannot wrap grid elements inside a row. Such as, 12-col, 6-col, 6-col
- Nesting the grid now works differently. A nested grid should still follow the global column layout and not be relative to its parent
- Columns don't have bottom margin so columns that has wrapped now touch each other vertically

We have decided to reinstall the old grid mechanism, maintaining the new class names. The only addition to the documentation will be adding `last-col` back in.

We can continue to develop a better grid using the new grid as a base. Until we have all concerns addressed.

**Comment by barrymcgee** [comment] 2017-01-09 12:19
I'm not sure I understand - why _should_ you be able to place elements into a row that exceed the total of.. say 12 (or whatever the max number of columns in the grid should be)? 

Given that in v1, rows are used purely for grid structure - what can't these be used to wrap elements?

**Comment by anthonydillon** [comment] 2017-01-10 09:24
TBH, I forgot the strips component and we could add the vertical padding to that component.

Although, I was under the impression that we replaced the grid to solve some small issues and to remove the `last-col` mechanism. Which I agree would be nice to remove. But this implemention results in more markup by wrapping each row in a `row` div. 

That said. I would like to hold of rolling back and take sometime this week to hash together some examples and alternatives. Then report back for a further discussion.

**Comment by barrymcgee** [comment] 2017-01-10 16:58
We moved away from the old grid as it was the root cause of a lot of layout bugs - mainly because of rounding errors in responsive layouts. 

The old grid was generated using Gridinator which admits as much at the bottom of their homepage - http://gridinator.com - meaning these bugs were inherent, hence the move to a more comprehensive and mature solution. 

Extra row containers may be needed here and there and while, yes, markup should be kept as lean as possible - being explicit and transparent is preferable to hidden (and brittle) complexity. Until Grid Layout lands everywhere we care about - we'll always have to accept such trade-offs.

**Comment by richmccartney** [comment] 2017-01-12 09:31
@barrymcgee @anthonydillon @yaili Can I suggest on the 25th we do a workshop on this to address the issues found in the new grid solution. We can look at ways to possibly improve all the issues found and proposed here.

I did speak to @anthonydillon saying there is a way to get rid of the ```last-col``` wrapping where all elements have guttering each side. This can scale further when nested so we don't get the wrapping issue there too.

**Comment by yaili** [comment] 2017-01-12 09:48
Good idea. I'll set it up.

**Comment by anthonydillon** [comment] 2017-01-12 10:23
Due to this needing more discussion I have set this back to Proposal and will report back with the result of the discussion.

**Comment by barrymcgee** [comment] 2017-01-27 09:57
This ticket has been addressed by recent discussions on grid.

**Closed** 2017-01-27 09:57 UTC
Labels: WG: Proposal
